# Variables
@base_url = http://localhost:3333

# Health Check
GET {{base_url}}/health

###

# Get rooms
GET {{base_url}}/rooms

###

# Create room
POST {{base_url}}/room
Content-Type: application/json

{
  "name": "Teste",
  "description": "Descrição da sala"
}